---
- hosts: all
  tasks:
    - name: Install ntpd service
      apt:
        name: ntpd
        state: present
      become: yes
    - name: Start service ntpd, if not started
      service:
        name: ntpd
        state: started
      become: yes