---
- hosts: all
  tasks:
    - name: Install ntpdate service
      apt:
        name: ntpdate
        state: present
    - name: Start service ntpdate, if not started
      service:
        name: ntpdate
        state: started