---
- hosts: all
  tasks:
    - name: Install ntp service
      apt:
        name: ntp
        state: present
      become: yes
    - name: Start service ntp, if not started
      service:
        name: ntp
        state: started
      become: yes